<!Doctype html>
<html>
<head>
    <meta name="viewport"
          content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>DEV.YESHTML5.COM</title>
    <link rel="shortcut icon" type="image/gif" href="<?= theme(); ?>src/images/common/favicon.gif">
    <link rel="shortcut icon" type="image/gif" href="<?= theme(); ?>src/images/common/favicon.png">
    <!--[style]-->
    <link type="text/css" rel="stylesheet" href="<?= theme(); ?>src/css/fontawesome.css"/>
    <link type="text/css" rel="stylesheet" href="<?= theme(); ?>src/css/basic.css"/>
    <link type="text/css" rel="stylesheet" href="<?= theme(); ?>src/css/common.css"/>
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,400">
    <!--[javascript]-->
    <script type="text/javascript" src="<?= theme(); ?>src/js/jquery.js"></script>
    <script type="text/javascript" src="<?= theme(); ?>src/js/lib.masonry.js"></script>
    <script type="text/javascript" src="<?= theme(); ?>src/js/core.js"></script>
    <script type="text/javascript" src="<?= theme(); ?>src/js/common.js"></script>
    <script type="text/javascript" src="/php/src/js/common.js"></script>
</head>
<body>